-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 14:10:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bankAccounts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankAccounts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankAccounts` DEFAULT CHARACTER SET utf8 ;
USE `bankAccounts` ;

-- -----------------------------------------------------
-- Table `bankAccounts`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankAccounts`.`Users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `Balance` FLOAT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankAccounts`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankAccounts`.`Transactions` (
  `TransactionId` INT NOT NULL AUTO_INCREMENT,
  `Amount` FLOAT NULL,
  `Date` DATETIME NULL,
  `Users_UserId` INT NOT NULL,
  PRIMARY KEY (`TransactionId`),
  INDEX `fk_Transactions_Users_idx` (`Users_UserId` ASC),
  CONSTRAINT `fk_Transactions_Users`
    FOREIGN KEY (`Users_UserId`)
    REFERENCES `bankAccounts`.`Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
